### ISSUE TITLE
ReplicaCount 2 Filestore

### ISSUE THREAD

**Issue by shazada** [Alfresco/acs-deployment#1034]
We want to set the FileStore to replica Count to 2, but the pvc is read-wirte-once

How can we set this to HA?
```
  filestore:
    # -- Declares the alfresco-shared-file-store used by the content repository
    # and transform service
    enabled: true
    replicaCount: 1
    image:
      repository: quay.io/alfresco/alfresco-shared-file-store
      tag: 3.1.0-M1
    persistence:
      # -- Persist filestore data
      enabled: true
      data:
        mountPath: "/tmp/Alfresco"
        subPath: "alfresco-content-services/filestore-data"
```

**Comment by alxgomz** [comment]
Hi @shazada 
you should be good to go with something like:

```yaml
filestore:
  persistence:
    enabled: true
    accessModes:
      - ReadWriteMany
    storageClass: myMultiRWClass
```
