### ISSUE TITLE
Helm deployment Error

### ISSUE THREAD

**Issue by panzerj** [Alfresco/acs-deployment#1117]
I want to deploy the alfresco-content-services helm chart. When I use kustomize everything works. But when I wrap It in an umbrella chart, define alfresco-content-services as a dependency and deploy using helm (with exactly the same values.yaml), i get the error:

`Error: template: hmi-alfresco/charts/alfresco-content-services/templates/config-infrastructure.yaml:29:49: executing "hmi-alfresco/charts/alfresco-content-services/templates/config-infrastructure.yaml" at <include "alfresco-search-service.deployment.name" .>: error calling include: template: no template "alfresco-search-service.deployment.name" associated with template 
"gotpl"
`

[test.zip](https://github.com/Alfresco/acs-deployment/files/14612255/test.zip)

**Comment by pmacius** [comment]
If you are declaring acs as a dependency you need to correctly adjust the values. See: https://helm.sh/docs/chart_template_guide/subcharts_and_globals/#overriding-values-from-a-parent-chart
So your values would be like this:

```
alfresco-content-services:
  activemq:
    enabled: false

  messageBroker:
    # -- Enable using an external message broker for Alfresco Content Services. Must disable `activemq.enabled`.
    url: "failover:(nio://activemq:61616)?timeout=3000"

  alfresco-control-center:
    enabled: false
  .
  .
  .
```
I hope this helps
