### ISSUE TITLE
Docker-compose port 8080 on proxy throw the error : org.apache.coyote.AbstractProcessor.parseHost The host [:8080] is not valid

### ISSUE THREAD

**Issue by crouUux** [Alfresco/acs-deployment#1317]
Hello guys, i'm trying to run the docker-compose into my server machine, when using it in my local machine everything is OK but when i run it on my server machine i'm getting this error on the alfresco container : 

```
org.apache.coyote.AbstractProcessor.parseHost The host [:8080] is not valid

 Note: further occurrences of request parsing errors will be logged at DEBUG level.

	java.lang.IllegalArgumentException

		at org.apache.tomcat.util.http.parser.Host.parse(Host.java:74)

		at org.apache.tomcat.util.http.parser.Host.parse(Host.java:43)

		at org.apache.coyote.AbstractProcessor.parseHost(AbstractProcessor.java:297)

		at org.apache.coyote.http11.Http11Processor.prepareRequest(Http11Processor.java:785)

		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:368)

		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)

		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:894)

		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1741)

		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)

		at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)

		at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)

		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

		at java.base/java.lang.Thread.run(Thread.java:833)
```

The problem is in the proxy port 8080:8080 when i remove it the error disapear but my share container is not accessible anymore : 

![Image](https://github.com/user-attachments/assets/e2cde7ba-223f-4824-8075-88b6bf9dfbd0)

Here is my docker-compose : 

```
services:
  alfresco:
    image: docker.io/alfresco/alfresco-content-repository-community:23.1.0
    mem_limit: 1900m
    environment:
      JAVA_TOOL_OPTIONS: >-
        -Dencryption.keystore.type=JCEKS
        -Dencryption.cipherAlgorithm=DESede/CBC/PKCS5Padding
        -Dencryption.keyAlgorithm=${ALFRESCO_KEY_ALGORITHM}
        -Dencryption.keystore.location=/usr/local/tomcat/shared/classes/alfresco/extension/keystore/keystore
        -Dmetadata-keystore.password=${ALFRESCO_KEY_STORE_PASSWORD}
        -Dmetadata-keystore.aliases=metadata
        -Dmetadata-keystore.metadata.password=${ALFRESCO_KEY_STORE_METADATA_PASSWORD}
        -Dmetadata-keystore.metadata.algorithm=DESede
      JAVA_OPTS: >-
        -Ddb.driver=org.postgresql.Driver
        -Ddb.username=${ALFRESCO_USERNAME}
        -Ddb.password=${ALFRESCO_PASSWORD}
        -Ddb.url=jdbc:postgresql://postgres:5432/alfresco
        -Dsolr.host=solr6
        -Dsolr.port=8983
        -Dsolr.http.connection.timeout=1000
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dsolr.base.url=/solr
        -Dindex.subsystem.name=solr6
        -Dshare.host=localhost
        -Dshare.port=8080
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dcsrf.filter.enabled=false
        -Daos.baseUrlOverwrite=http://localhost:8080/alfresco/aos
        -Dmessaging.broker.url="failover:(nio://activemq:61616)?timeout=3000&jms.useCompression=true"
        -Ddeployment.method=DOCKER_COMPOSE
        -DlocalTransform.core-aio.url=http://transform-core-aio:8090/
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    volumes:
      - /usr/local/cosy/alfresco/alfresco-data:/usr/local/tomcat/alf_data
      - /usr/local/cosy/alfresco/alfresco-logs:/usr/local/tomcat/logs
  transform-core-aio:
    image: alfresco/alfresco-transform-core-aio:5.0.0
    mem_limit: 2536m
    environment:
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
    ports:
      - "8090:8090"
  share:
    image: alfresco-share-image-customise
    mem_limit: 1g
    environment:
      REPO_HOST: "alfresco"
      REPO_PORT: "8080"
      JAVA_OPTS: >-
        -XX:MinRAMPercentage=50
        -XX:MaxRAMPercentage=80
        -Dalfresco.host=localhost
        -Dalfresco.port=8080
        -Dalfresco.context=alfresco
        -Dalfresco.protocol=http
  postgres:
    image: postgres:14.4
    mem_limit: 512m
    environment:
      - POSTGRES_PASSWORD=${ALFRESCO_PASSWORD}
      - POSTGRES_USER=${ALFRESCO_USERNAME}
      - POSTGRES_DB=alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "5432:5432"
    volumes:
      - /usr/local/cosy/alfresco/postgres-data:/var/lib/postgresql/data
  solr6:
    image: docker.io/alfresco/alfresco-search-services:2.0.8.2
    mem_limit: 2g
    environment:
      SOLR_ALFRESCO_HOST: "alfresco"
      SOLR_ALFRESCO_PORT: "8080"
      SOLR_SOLR_HOST: "solr6"
      SOLR_SOLR_PORT: "8983"
      SOLR_CREATE_ALFRESCO_DEFAULTS: "alfresco,archive"
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: >-
        -Dalfresco.secureComms.secret=secret
    ports:
      - "8083:8983"
    volumes:
      - /usr/local/cosy/alfresco/solr-data:/opt/alfresco-search-services/data
  activemq:
    image: alfresco/alfresco-activemq:5.17.1-jre11-rockylinux8
    mem_limit: 1g
    ports:
      - "8161:8161" # Web Console
      - "5672:5672" # AMQP
      - "61616:61616" # OpenWire
      - "61613:61613" # STOMP
    volumes:
      - /usr/local/cosy/alfresco/activemq-data:/var/activemq
  content-app:
    image: alfresco/alfresco-content-app:4.3.0
    mem_limit: 128m
    environment:
      APP_BASE_SHARE_URL: "http://localhost:8080/aca/#/preview/s"
  control-center:
    image: quay.io/alfresco/alfresco-control-center:8.3.0
    mem_limit: 128m
    environment:
      APP_CONFIG_PROVIDER: "ECM"
      APP_CONFIG_AUTH_TYPE: "BASIC"
      BASE_PATH: ./
  proxy:
    image: alfresco/alfresco-acs-nginx:3.4.2
    mem_limit: 128m
    environment:
      DISABLE_PROMETHEUS: "true"
      DISABLE_SYNCSERVICE: "true"
      DISABLE_ADW: "true"
      ENABLE_CONTENT_APP: "true"
    depends_on:
      - alfresco
      - content-app
      - control-center
    ports:
      - "8080:8080"
    links:
      - content-app
      - alfresco
      - share
      - control-center
volumes:
  alfresco-data:
  alfresco-logs:
  share-logs:
  postgres-data:
  solr-data:
  activemq-data:
```

can someone help please ??
