### ISSUE TITLE
Use of TCP for health and liveness causing heaps of warnings in logs

### ISSUE THREAD

**Issue by cijujoseph** [Alfresco/acs-deployment#443]
Use of the TCP port for activemq health and liveness probes is causing a lot of warnings appear in the logs.
`WARN | Transport Connection to: tcp://10.244.0.1:40890 failed: java.io.EOFException`

The following
```
tcpSocket:
         port: {{ .Values.services.broker.ports.internal.openwire | default 61616 }}
```
can be substituted with the health endpoint api
```
          httpGet:
            path: "/api/jolokia/read/org.apache.activemq:type=Broker,brokerName={{ template "activemq.fullname" . }},service=Health"
            port: {{ .Values.services.webConsole.ports.internal.webConsole | default 8161 }}
            httpHeaders:
              - name: Authorization
                value: Basic {{ (printf "%s:%s" .Values.adminUser.username .Values.adminUser.password ) | b64enc}}
```
