### ISSUE TITLE
SOLR: change pods replacement strategy

### ISSUE THREAD

**Issue by dkekel** [Alfresco/acs-deployment#627]
Hi,

Currently Solr deployment using `RollingUpdate` pod replacement strategy. This results in a new pod starting up while the old one is still up. Since Solr is using file system locks (`write.lock` files in the index folders), the new pod starts in an erroneous state due to existing locks on the indexes.

If the strategy is set to `Recreate`, the new pod will only start after the previous one is terminated. This is useful for the charts re-sync.

Another problem is if the pod is deleted using `kubectl` for example. In that case the new one still starts up while the old in is terminating causing the same issue with the index locks.

Potentially there can be an additional initContainer that would clean-up the locks. Something like (the command template is pseudo-code)
```
name: lock-clean-up
    image: busybox
    command: ["sh", "-c", "rm -v {{ .Values.persistence.search.data.mountPath }}/alfresco/index/write.lock {{ .Values.persistence.search.data.mountPath }}/archive/index/write.lock"]
    volumeMounts:
      - name: data
        mountPath: {{ .Values.persistence.search.data.mountPath }}
```

Cheers,
Dmitry
