### ISSUE TITLE
ACS community edition on k8s cluster - SOLR pvc

### ISSUE THREAD

**Issue by Kiiupi** [Alfresco/acs-deployment#628]
Hello

Me and my teams are trying to deploy ACS community edition using helm chart, on a k8s cluster provided by a Host company (not AWS or Azure).

We already have others applications on this cluster and so we already have a volume provider on specific path which we want to use for ACS installation. 

Using the instructions provided on documentation, we had customised value to match with our environment, but, SOLR pvc not allow complete customization on `storageClassName`.

In fact, in template, classPathName is defined as it : 
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr-claim
  labels:
    app: {{ template "alfresco-search.fullName" . }}-solr
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: search
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: {{ .Values.persistence.VolumeSizeRequest }}
  {{- if .Values.persistence.EbsPvConfiguration.volumeID }}
  storageClassName: {{ template "alfresco-search.fullName" . }}-solr-sc
  {{- end }}
```
So as is we cannot customize `storageClassName` via values. In first time to resolve this situation we edit template file and add this lines :

``` yaml
  {{- else if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
```
But we are conscious this is not a long time solution, so we are wondering if there is another way to modify this parameter in case this behavior is normal or if its problem is an issue/bug which was not planned in first time.

Thank for your help.
