### ISSUE TITLE
Missing `common.ingress.` templates in 5.2.0

### ISSUE THREAD

**Issue by dkekel** [Alfresco/acs-deployment#700]
Hi,

I'm trying to deploy Alfresco Helm v5.2.0, but I'm facing an issue. Every ingress chart relies on the following templates: "common.capabilities.ingress.apiVersion", "common.ingress.supportsPathType" and "common.ingress.backend".

Those templates do not exist in the v5.2.0. I don't see anything related in the documentation.

Should I include an additional chart dependency? Or were those templates simply forgotten in the commit?

Thanks

**Comment by dkekel** [comment]
OK, it looks like this dependency is requires:
```
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 1.8.0
```

It is probably worth mentioning it in the documentation.

**Comment by alxgomz** [comment]
Hi @dkekel ,
This dependency should be fulfilled by the `alfresco-search` or the `alfresco-sync-service` subchart (or the `postgresql` which is itself a bitnami dep) . That's the main reason why in 5.2.0 charts `alfresco-search` doesn't have a condition to disable it and is considered mandatory.
Did you remove that dependency in some way? If so then yes, you need to add that dependency manually. If not... then we most likely have another issue to investigate and in that case we'd need more info from you.

Though we recognize current dependency management is not optimal and aim at improving it

**Comment by dkekel** [comment]
Hi @alxgomz ,

Not really, I'm simply importing the main Alfresco chart without any additional changes (below is my complete Chart.yaml):
```
name: XXXX-helm
description: XXXX ArgoCD deployment
version: XXXX
apiVersion: v2
keywords:
  - XXXX

dependencies:
  - name: alfresco-content-services
    version: 5.2.0
    repository: https://kubernetes-charts.alfresco.com/stable

```

This didn't work, resulting in the error that indicated missing templates. It was fixed when I explicitly added the `bitnami` dependency as mentioned in my previous comment.
