### ISSUE TITLE
failed to deploy "alfresco/alfresco-content-services" helmchart with community_values

### ISSUE THREAD

**Issue by JuliusDigel** [Alfresco/acs-deployment#890]
Hey!
so im trying to deploy alfresco via helmchart to a locally managed kubernetes instance. I tried my own k3s-cluster aswell as the suggested installation route via docker-desktop https://github.com/Alfresco/acs-deployment/blob/master/docs/helm/docker-desktop-deployment.md.

In both installation routines i get these errors:

1. `Error: INSTALLATION FAILED: execution error at (alfresco-content-services/charts/alfresco-search/templates/secret-solr-jtoolopt.yml:12:51): You need to provide a shared secret for Solr/repo authentication , see https://github.com/Alfresco/acs-deployment/tree/master/docs/helm`
This one is just a outdated documentation i think since its easily fixable with adding "--set global.tracking.sharedsecret=$(openssl rand -hex 24)" 

2. `coalesce.go:223: warning: destination for postgresql.persistence.storageClass is a table. Ignoring non-table value ()` Could it be that the value "null" under the following part of the helmchart is outdated`?
```
persistence:
    # -- set the storageClass to use for dynamic provisioning.
    # setting it to null means "default storageClass".
    storageClass: null
    # -- provide an existing persistent volume claim name to persist SQL data
    # Make sure the root folder has the appropriate permissions/ownhership set.
    existingClaim: null
    subPath: "alfresco-content-services/database-data"
```
When deploying the installation follows through but t the activemq & cs-repository containers are stuck and eventually the whole helm-installation is failing with this error message `Error: INSTALLATION FAILED: release acs failed, and has been uninstalled due to atomic being set: timed out waiting for the condition`

![grafik](https://user-images.githubusercontent.com/26574801/218736599-909502b4-7fab-4dbc-bddd-38d69df88b33.png)

The last log-entries of the activemq container are the following:
```2023-02-14 11:40:14,231 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2023-02-14 11:40:14,231 main ERROR Null object returned for RollingRandomAccessFile in Appenders.
2023-02-14 11:40:14,233 main ERROR Unable to locate appender "RollingFile" for logger config "root"
2023-02-14 11:40:14,234 main ERROR Unable to locate appender "AuditLog" for logger config "org.apache.activemq.audit"
Loading message broker from: xbean:activemq.xml 
INFO | Using Persistence Adapter: KahaDBPersistenceAdapter[/opt/activemq/data/kahadb]
INFO | Database /opt/activemq/data/kahadb/lock is locked by another server. This broker is now in slave mode waiting a lock to be acquired 
```

These are the full logs of the two pods which are not working properly:

[acs-activemq-7db859c48-s7jzg_activemq.log](https://github.com/Alfresco/acs-deployment/files/10732271/acs-activemq-7db859c48-s7jzg_activemq.log)

[acs-alfresco-cs-repository-6d65bb74d4-s6z2t_alfresco-content-services.log](https://github.com/Alfresco/acs-deployment/files/10732272/acs-alfresco-cs-repository-6d65bb74d4-s6z2t_alfresco-content-services.log)

Thanks for the help!
