### ISSUE TITLE
Configure alfresco-global.properties file using helm

### ISSUE THREAD

**Issue by gnieser** [Alfresco/acs-deployment#989]
Hello,

I'm trying to deploy Alfresco on Kubernetes using the Helm charts.
There are many properties to configure in alfresco-global.properties.

Unfortunately, it's not clear tome how I can set them my own alfresco-global.properties through helm charts.

From what I see, the alfresco-global.properties is mounted from a volume
```yaml
volumeMounts:
{{- if and (index .Values "alfresco-search" "enabled") (eq .Values.global.tracking.auth "secret") }}
- name: repository-properties
  mountPath: /usr/local/tomcat/shared/classes/alfresco-global.properties
  subPath: alfresco-global.properties
{{- end }}
```

The volume comes from the `alfresco-repository-properties-secret` secret
```yaml
{{- if and (index .Values "alfresco-search" "enabled") (eq .Values.global.tracking.auth "secret") }}
  - name: repository-properties
    secret:
      secretName: {{ template "alfresco.shortname" . }}-repository-properties-secret
      defaultMode: 0400
      items:
        - key: alfresco-global.properties
          path: alfresco-global.properties
{{- end }}
```

But the secret is not extensible, it only defines the solr-sharedSecret.
```yaml
{{- if and (index .Values "alfresco-search" "enabled") (eq .Values.global.tracking.auth "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "alfresco.shortname" . }}-repository-properties-secret
  labels:
    {{- include "repository.labels" . | nindent 4 }}
type: Opaque
data:
  alfresco-global.properties: {{ printf "%s%s" "solr.sharedSecret=" (include "tracking-shared-secret" .) | b64enc | quote }}
{{- end }}
```

I'm looking at configuring properties such as `authentication.chain`, `identity-service.*`. It works fine if I manually edit the created secret after deployment but this defeats the purpose of Helm charts and GitOps.

Could you please point me towards a solution?
Thanks
